export type Plant = 'ave' | 'real';
export type Route = { id:string; farm:string; shed:string; city:string; birds:number; emptyMin:number; aveMin:number|null; realMin:number|null; destination:'both'|Plant; blockedUntil:string; source:'demo'|'manual'|'import' };
export type Truck = {id:string; name:string; status:'available'|'maintenance'; note:string};
export type Config = {date:string; days:number; fleet:number; unavailable:number; boxes:number; density:number; loadMin:number; residenceMin:number; unloadMin:number; returnMin:number; delayMin:number; aveTarget:number; realTarget:number; aveOpen:number; aveClose:number; realOpen:number; realClose:number; saturdayTarget:number; saturdayClose:number; nightOnly:boolean; nightStart:number; nightEnd:number; creationLoss:number; stockMode:'available'|'housed'};
export type Trip = {id:string; day:number; plant:Plant; routeId:string; farm:string; shed:string; city:string; truck:string; birds:number; start:number; loadStart:number; loadedStart:number; arrival:number; dock:number; end:number; due:number; emptyMin:number; loadedMin:number; wait:number};
export type Result = {trips:Trip[]; requested:number; delivered:number; peak:number; active:number; workHours:number; avgCycle:number; left:number; missedSlots:number; days:{day:number; date:string; requested:number; delivered:number; trips:number}[]; plants:Record<Plant,{requested:number; delivered:number; trips:number; dockMinutes:number; window:number}>; hourly:{hour:number; busy:number; delivered:number}[]; excluded:number};
export type LossRecord={id:string; date:string; plant:Plant; routeId:string; truck:string; loaded:number; dead:number; minutes:number; note:string};
export type Snapshot={id:string; name:string; createdAt:string; config:Config; routes:Route[]; trucks:Truck[]; summary:{delivered:number; requested:number; trips:number; peak:number}};
export type Workspace={schema:1;config:Config;routes:Route[];trucks:Truck[];records:LossRecord[];scenarios:Snapshot[]};
export const defaultConfig:Config={date:'2026-10-05',days:1,fleet:22,unavailable:2,boxes:627,density:6,loadMin:90,residenceMin:90,unloadMin:25,returnMin:75,delayMin:0,aveTarget:130000,realTarget:90000,aveOpen:360,aveClose:1380,realOpen:360,realClose:990,saturdayTarget:60000,saturdayClose:780,nightOnly:false,nightStart:1140,nightEnd:360,creationLoss:10,stockMode:'available'};
const cities=['Pará de Minas','Igaratinga','Conceição do Pará','São Gonçalo do Pará','São Sebastião do Oeste','Itaúna','Formiga','Itapecerica','Cordisburgo','Pedra do Indaiá','Onça de Pitangui','Nova Serrana'];
export function createWorkspace():Workspace{return {schema:1,config:{...defaultConfig},routes:cities.map((city,i)=>({id:`demo-${i+1}`,farm:`Granja demonstração ${String(i+1).padStart(2,'0')}`,shed:`D${String(i+1).padStart(2,'0')}`,city,birds:26000+(i%4)*5000,emptyMin:[65,80,90,70,100,50,130,140,240,135,85,100][i],aveMin:[120,150,160,140,190,140,250,270,360,230,170,190][i],realMin:[135,135,175,150,170,155,230,250,340,240,150,170][i],destination:'both',blockedUntil:'',source:'demo'})),trucks:Array.from({length:22},(_,i)=>({id:`TB-${String(i+1).padStart(2,'0')}`,name:`TB-${String(i+1).padStart(2,'0')}`,status:'available',note:''})),records:[],scenarios:[]};}
export const fmt=(n:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(n);
export const pct=(n:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(n)+'%';
export function clock(n:number){const day=Math.floor(n/1440),m=((Math.round(n)%1440)+1440)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}${day===0?'':day<0?' · D'+day:' · D+'+day}`;}
export function datePlus(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export function nightLoad(t:number,duration:number,start:number,end:number){const day=Math.floor(t/1440);for(let d=day-1;d<=day+3;d++){const a=d*1440+start,b=d*1440+(end>start?end:end+1440);const candidate=Math.max(t,a);if(candidate+duration<=b)return candidate;}throw new Error('Não há janela noturna suficiente para carregar.');}
export function validateConfig(c:Config){const ranges:Partial<Record<keyof Config,[number,number]>>={days:[1,45],fleet:[1,100],unavailable:[0,100],boxes:[1,1000],density:[1,8],loadMin:[1,600],residenceMin:[1,600],unloadMin:[1,300],returnMin:[1,600],delayMin:[0,360],aveTarget:[0,500000],realTarget:[0,500000],aveOpen:[0,1439],aveClose:[1,1440],realOpen:[0,1439],realClose:[1,1440],saturdayTarget:[0,500000],saturdayClose:[1,1440],nightStart:[0,1439],nightEnd:[0,1439],creationLoss:[0,100]};for(const[k,[lo,hi]]of Object.entries(ranges)){const v=c[k as keyof Config];if(typeof v!=='number'||!Number.isFinite(v)||v<lo||v>hi)throw new Error(`Parâmetro inválido: ${k}.`);}if(!/^\d{4}-\d{2}-\d{2}$/.test(c.date)||!Number.isFinite(Date.parse(c.date+'T12:00:00Z')))throw new Error('Data inválida.');if(c.aveClose<=c.aveOpen||c.realClose<=c.realOpen)throw new Error('O encerramento deve ocorrer depois da abertura.');if(c.unloadMin>c.residenceMin)throw new Error('Descarga não pode superar a permanência no frigorífico.');if(c.stockMode!=='available'&&c.stockMode!=='housed')throw new Error('Base de aves inválida.');if(c.nightOnly){const duration=(c.nightEnd-c.nightStart+1440)%1440;if(!duration||c.loadMin>duration)throw new Error('A janela de carregamento é menor que o tempo de carga.');}}
export function simulate(c:Config,routes:Route[],trucks:Truck[]):Result{
 validateConfig(c);const capacity=Math.floor(c.boxes)*Math.floor(c.density);const activeTrucks=trucks.slice(0,Math.floor(c.fleet)).filter(t=>t.status==='available');const active=Math.max(0,activeTrucks.length-Math.floor(c.unavailable));const names=activeTrucks.slice(0,active).map(t=>t.id);const free=names.map(()=>-1440);const stock=routes.map(r=>Math.max(0,Math.floor(r.birds*(c.stockMode==='housed'?1-c.creationLoss/100:1))));
 const trips:Trip[]=[];const plants={ave:{requested:0,delivered:0,trips:0,dockMinutes:0,window:0},real:{requested:0,delivered:0,trips:0,dockMinutes:0,window:0}};const days:Result['days']=[];let missedSlots=0;
 for(let day=0;day<c.days;day++){const date=datePlus(c.date,day),weekday=new Date(date+'T12:00:00Z').getUTCDay(),offset=day*1440;const slots:{plant:Plant;due:number;close:number}[]=[];const remaining={ave:0,real:0};
 for(const plant of ['ave','real']as Plant[]){const open=c[plant==='ave'?'aveOpen':'realOpen'];const close=weekday===6?c.saturdayClose:c[plant==='ave'?'aveClose':'realClose'];const demand=weekday===0?0:Math.floor(weekday===6?c.saturdayTarget:c[plant==='ave'?'aveTarget':'realTarget']);remaining[plant]=demand;plants[plant].requested+=demand;plants[plant].window+=demand?Math.max(0,close-open):0;const count=Math.ceil(demand/capacity);for(let i=0;i<count;i++)slots.push({plant,due:offset+open+i*Math.max(0,close-open-c.unloadMin)/Math.max(1,count-1),close:offset+close});}
 const request=remaining.ave+remaining.real;slots.sort((a,b)=>a.due-b.due);const before=trips.length;
 // Extra passes use unfilled dock opportunities after partial loads; no implicit mixing of barns.
 const attempts=[...slots];let extras=0;
 for(let si=0;si<attempts.length;si++){const slot=attempts[si];if(remaining[slot.plant]<=0)continue;let best:{ri:number;ti:number;start:number;loadStart:number;loadedStart:number;arrival:number;dock:number;end:number;loadedMin:number;birds:number}|null=null;
 const previous=trips.filter(t=>t.day===day&&t.plant===slot.plant);const dockFree=previous.length?previous[previous.length-1].dock+c.unloadMin:offset+c[slot.plant==='ave'?'aveOpen':'realOpen'];
 for(let ri=0;ri<routes.length;ri++){const r=routes[ri];const travel=r[slot.plant==='ave'?'aveMin':'realMin'];if(stock[ri]<=0||r.blockedUntil&&r.blockedUntil>=date||r.destination!=='both'&&r.destination!==slot.plant||travel===null||!Number.isFinite(travel))continue;const loadedMin=travel+c.delayMin;const pre=r.emptyMin+c.loadMin+loadedMin;for(let ti=0;ti<free.length;ti++){let start=Math.max(free[ti],slot.due-pre);let loadStart=start+r.emptyMin;if(c.nightOnly){loadStart=nightLoad(loadStart,c.loadMin,c.nightStart,c.nightEnd);start=loadStart-r.emptyMin;}const loadedStart=loadStart+c.loadMin,arrival=loadedStart+loadedMin,dock=Math.max(arrival,dockFree,slot.due);if(dock+c.unloadMin>slot.close+0.001)continue;const end=dock+c.residenceMin+c.returnMin,birds=Math.min(capacity,stock[ri],remaining[slot.plant]);if(!best||dock<best.dock-.01||Math.abs(dock-best.dock)<.01&&(birds>best.birds||birds===best.birds&&end-start<best.end-best.start))best={ri,ti,start,loadStart,loadedStart,arrival,dock,end,loadedMin,birds};}}
 if(!best){missedSlots++;continue;}const b=best,r=routes[b.ri];stock[b.ri]-=b.birds;remaining[slot.plant]-=b.birds;free[b.ti]=b.end;const trip={id:`V${String(trips.length+1).padStart(4,'0')}`,day,plant:slot.plant,routeId:r.id,farm:r.farm,shed:r.shed,city:r.city,truck:names[b.ti],birds:b.birds,start:b.start,loadStart:b.loadStart,loadedStart:b.loadedStart,arrival:b.arrival,dock:b.dock,end:b.end,due:slot.due,emptyMin:r.emptyMin,loadedMin:b.loadedMin,wait:Math.max(0,b.dock-b.arrival)};trips.push(trip);plants[slot.plant].delivered+=b.birds;plants[slot.plant].trips++;plants[slot.plant].dockMinutes+=c.unloadMin;
 if(b.birds<capacity&&remaining[slot.plant]>0&&extras<routes.length*2){attempts.push({...slot,due:b.dock+c.unloadMin});extras++;}
 }
 days.push({day,date,requested:request,delivered:request-remaining.ave-remaining.real,trips:trips.length-before});}
 const events=trips.flatMap(t=>[{time:t.start,delta:1},{time:t.end,delta:-1}]).sort((a,b)=>a.time-b.time||a.delta-b.delta);let current=0,peak=0;for(const e of events){current+=e.delta;peak=Math.max(peak,current);}const requested=plants.ave.requested+plants.real.requested,delivered=plants.ave.delivered+plants.real.delivered,workHours=trips.reduce((s,t)=>s+(t.end-t.start)/60,0);const hourly=Array.from({length:25},(_,hour)=>({hour,busy:trips.filter(t=>t.start<=hour*60&&t.end>hour*60).length,delivered:trips.filter(t=>t.dock+c.unloadMin<=hour*60&&t.day===0).reduce((s,t)=>s+t.birds,0)}));
 return{trips,requested,delivered,peak,active,workHours,avgCycle:trips.length?workHours*60/trips.length:0,left:stock.reduce((a,b)=>a+b,0),missedSlots,days,plants,hourly,excluded:routes.filter(r=>r.aveMin===null&&r.realMin===null).length};
}
export function validateRoute(r:Route){if(!r.id||!r.farm?.trim()||!r.shed?.trim()||!r.city?.trim())throw new Error('Preencha granja, galpão e cidade.');if(!Number.isInteger(r.birds)||r.birds<0||r.birds>10000000)throw new Error('Quantidade de aves inválida.');if(!Number.isFinite(r.emptyMin)||r.emptyMin<0||r.emptyMin>1440)throw new Error('Tempo vazio inválido.');for(const t of [r.aveMin,r.realMin])if(t!==null&&(!Number.isFinite(t)||t<0||t>1440))throw new Error('Tempo carregado inválido.');if(!['both','ave','real'].includes(r.destination))throw new Error('Destino inválido.');if(r.blockedUntil&&!/^\d{4}-\d{2}-\d{2}$/.test(r.blockedUntil))throw new Error('Data de bloqueio inválida.');}
export function validateWorkspace(w:Workspace){if(w.schema!==1||!Array.isArray(w.routes)||w.routes.length>2000||!Array.isArray(w.trucks)||w.trucks.length>100||!Array.isArray(w.records)||w.records.length>10000||!Array.isArray(w.scenarios)||w.scenarios.length>30)throw new Error('Arquivo de trabalho incompatível ou acima do limite.');validateConfig(w.config);w.routes.forEach(validateRoute);const ids=new Set();for(const r of w.routes){if(ids.has(r.id))throw new Error('Rotas com identificadores repetidos.');ids.add(r.id);}const tids=new Set();for(const t of w.trucks){if(!t.id||tids.has(t.id)||!['available','maintenance'].includes(t.status))throw new Error('Cadastro de frota inválido.');tids.add(t.id);}for(const r of w.records){if(!Number.isInteger(r.loaded)||r.loaded<=0||!Number.isInteger(r.dead)||r.dead<0||r.dead>r.loaded||!Number.isFinite(r.minutes)||r.minutes<0||!['ave','real'].includes(r.plant))throw new Error('Registro de transporte inválido.');}for(const s of w.scenarios){validateConfig(s.config);if(!Array.isArray(s.routes)||s.routes.length>2000||!Array.isArray(s.trucks)||s.trucks.length>100)throw new Error('Cenário inválido.');s.routes.forEach(validateRoute);}}
export function csvRows(text:string):string[][]{const delim=text.split(/\r?\n/)[0].includes(';')?';':',';const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===delim&&!quoted){row.push(cell.trim());cell='';}else if(c==='\n'&&!quoted){row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else if(c!=='\r')cell+=c;}if(quoted)throw new Error('CSV contém aspas sem fechamento.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows;}
export function parseRoutes(text:string){const rows=csvRows(text.replace(/^\uFEFF/,''));const header=rows.shift()?.map(h=>h.toLowerCase());const required=['granja','galpao','cidade','aves','vazio_min','ave_nova_min','real_min','destino'];if(!header||required.some(k=>!header.includes(k)))throw new Error('Use o modelo CSV: faltam colunas obrigatórias.');const errors:string[]=[];const routes:Route[]=[];const keys=new Set();rows.forEach((row,i)=>{try{const get=(k:string)=>row[header.indexOf(k)]??'';const farm=get('granja'),shed=get('galpao');const key=(farm+'|'+shed).toLocaleLowerCase('pt-BR');if(keys.has(key))throw new Error('Granja e galpão repetidos no arquivo.');keys.add(key);const r:Route={id:'imp-'+encodeURIComponent(key),farm,shed,city:get('cidade'),birds:Number(get('aves')),emptyMin:Number(get('vazio_min')),aveMin:get('ave_nova_min')===''?null:Number(get('ave_nova_min')),realMin:get('real_min')===''?null:Number(get('real_min')),destination:get('destino') as Route['destination'],blockedUntil:get('bloqueado_ate'),source:'import'};if(!get('aves')||!get('vazio_min'))throw new Error('Aves e tempo vazio são obrigatórios.');validateRoute(r);routes.push(r);}catch(e){errors.push(`Linha ${i+2}: ${(e as Error).message}`);}});if(rows.length>2000)errors.push('Limite de 2.000 linhas por importação.');return{routes,errors,total:rows.length};}
export function csvCell(v:unknown){const s=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')+'"';}
